import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  detailBtn: {
    borderWidth: 1,
    borderColor: '#5F2EEA',
    borderRadius: 4,
    padding: 10,
    width: 150,
  },
  detailBtnPress: {
    borderWidth: 1,
    backgroundColor: '#5F2EEA',
    borderColor: 'white',
    borderRadius: 4,
    padding: 10,
    width: 150,
  },
  details: {
    fontSize: 14,
    fontWeight: '300',
    color: '#5F2EEA',
    alignSelf: 'center',
  },
  detailsPress: {
    fontSize: 14,
    fontWeight: '300',
    color: 'white',
    alignSelf: 'center',
  },
  container: {
    padding: 20,
    backgroundColor: '#FFFFFF',
  },
  footer: {
    padding: 20,
    paddingTop: 50,
    backgroundColor: '#FFFFFF',
  },
  title: {
    color: '#752EEA',
    fontSize: 34,
    fontWeight: '700',
  },
  showing: {
    backgroundColor: '#D6D8E7',
    padding: 20,
    paddingTop: 48,
    paddingBottom: 40,
  },
  imageBorder: {
    padding: 10,
    borderWidth: 1,
    borderColor: 'white',
    borderRadius: 6,
    width: 145,
    marginEnd: 20,
  },
  imageCard: {
    padding: 10,
    marginEnd: 20,
    borderWidth: 1,
    borderColor: '#DEDEDE',
    borderRadius: 6,
    alignItems: 'center',
    width: 200,
  },
  image: {
    width: 150,
    height: 220,
    borderRadius: 6,
    resizeMode: 'cover',
  },
  input: {
    height: 64,
    borderWidth: 1,
    borderColor: '#DEDEDE',
  },
  commonText: {
    color: '#6E7191',
    fontSize: 12,
    fontWeight: '400',
  },
  genreText: {
    color: '#A0A3BD',
    fontSize: 11,
    fontWeight: '300',
    width: 150,
    flex: 1,
    textAlign: 'center',
  },
  titleText: {
    paddingTop: 10,
    color: 'black',
    fontSize: 14,
    fontWeight: '600',
    flex: 1,
    textAlign: 'center',
  },
});
